# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d48bbcce5bd1fa995e3283570cb8fbf343e610d49f66b3d80a09b47c3d9ffa323cd8df14b7000a18305e64bd77f55adc7650ed07830094120998833ede1fe86b

test:
  secret_key_base: 44a9f46493a519c81d1750cb5ee8530b66745b336f8203f72c753c24af9ab1e4e79505693c986cab6dd4464711e99e48034b0a6627fcc36b4abe83a289029765

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
